apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  selector:
    matchLabels:
      app: hello-go
  replicas: 3 
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: asia.gcr.io/k8s-day/hello-go:v1
        ports:
        - containerPort: 8080
